baseURL = "https:fjhskfs415263.github.io/myPoems/"
languageCode = "en-us"
title = "my poems"
theme = "hugo-book"



#[params]
#customCSS = ["css/custom.css"]


# Widgets 配置
[widgets]

  # 首页 widgets
  [[widgets.homepage]]
  type = "search"

  [[widgets.homepage]]
  type = "archives"
    [widgets.homepage.params]
    limit = 5

  [[widgets.homepage]]
  type = "categories"
    [widgets.homepage.params]
    limit = 10

  [[widgets.homepage]]
  type = "tag-cloud"
    [widgets.homepage.params]
    limit = 10

  # 页面 widgets
  [[widgets.page]]
  type = "toc"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
        unsafe = true
